apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http-healthz
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: http-admission
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
